import { DoctorProfile, Appointment, User, NotificationLog, MedicationReminder } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'usr_pat_1',
    name: 'Alex Johnson',
    email: 'alex.johnson@example.com',
    phone: '+1 (555) 234-5678',
    role: 'patient',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'usr_pat_2',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phone: '+1 (555) 345-6789',
    role: 'patient',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'usr_doc_1',
    name: 'Dr. Sarah Smith, MD',
    email: 'dr.smith@healthmanager.clinic',
    phone: '+1 (555) 101-2001',
    role: 'doctor',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'usr_doc_2',
    name: 'Dr. Marcus Vance, MD',
    email: 'dr.vance@healthmanager.clinic',
    phone: '+1 (555) 101-2002',
    role: 'doctor',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'usr_admin_1',
    name: 'Admin Elena Rostova',
    email: 'admin@healthmanager.clinic',
    phone: '+1 (555) 999-0000',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
  },
];

const DEFAULT_WORKING_HOURS = [
  { dayOfWeek: 1, dayName: 'Monday', startTime: '09:00', endTime: '17:00', isWorkingDay: true },
  { dayOfWeek: 2, dayName: 'Tuesday', startTime: '09:00', endTime: '17:00', isWorkingDay: true },
  { dayOfWeek: 3, dayName: 'Wednesday', startTime: '09:00', endTime: '17:00', isWorkingDay: true },
  { dayOfWeek: 4, dayName: 'Thursday', startTime: '09:00', endTime: '17:00', isWorkingDay: true },
  { dayOfWeek: 5, dayName: 'Friday', startTime: '09:00', endTime: '16:00', isWorkingDay: true },
  { dayOfWeek: 6, dayName: 'Saturday', startTime: '10:00', endTime: '14:00', isWorkingDay: false },
  { dayOfWeek: 0, dayName: 'Sunday', startTime: '10:00', endTime: '14:00', isWorkingDay: false },
];

export const SEED_DOCTORS: DoctorProfile[] = [
  {
    id: 'doc_1',
    userId: 'usr_doc_1',
    name: 'Dr. Sarah Smith, MD',
    email: 'dr.smith@healthmanager.clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    specialisation: 'Cardiology',
    experienceYears: 14,
    consultationFee: 150,
    rating: 4.9,
    reviewCount: 128,
    roomNumber: 'Suite 302-A',
    bio: 'Board-certified cardiologist specializing in preventive cardiovascular medicine, hypertension management, and heart rhythm disorders.',
    slotDurationMinutes: 30,
    workingHours: DEFAULT_WORKING_HOURS,
    leaveDays: [],
  },
  {
    id: 'doc_2',
    userId: 'usr_doc_2',
    name: 'Dr. Marcus Vance, MD',
    email: 'dr.vance@healthmanager.clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
    specialisation: 'Dermatology',
    experienceYears: 9,
    consultationFee: 120,
    rating: 4.8,
    reviewCount: 94,
    roomNumber: 'Suite 108',
    bio: 'Specialist in clinical and cosmetic dermatology, chronic eczema, acne protocols, and early skin lesion evaluations.',
    slotDurationMinutes: 30,
    workingHours: DEFAULT_WORKING_HOURS,
    leaveDays: [],
  },
  {
    id: 'doc_3',
    userId: 'usr_doc_3',
    name: 'Dr. Aisha Patel, MD',
    email: 'dr.patel@healthmanager.clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813581-22c53a73c1c4?auto=format&fit=crop&q=80&w=300',
    specialisation: 'Neurology',
    experienceYears: 16,
    consultationFee: 180,
    rating: 5.0,
    reviewCount: 210,
    roomNumber: 'Suite 415-B',
    bio: 'Expert neurologist focusing on migraine treatments, neuropathic pain management, sleep medicine, and cognitive health.',
    slotDurationMinutes: 45,
    workingHours: DEFAULT_WORKING_HOURS,
    leaveDays: [],
  },
  {
    id: 'doc_4',
    userId: 'usr_doc_4',
    name: 'Dr. Robert Chen, MD',
    email: 'dr.chen@healthmanager.clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300',
    specialisation: 'Pediatrics',
    experienceYears: 11,
    consultationFee: 100,
    rating: 4.9,
    reviewCount: 165,
    roomNumber: 'Suite 204',
    bio: 'Dedicated pediatrician offering comprehensive newborn care, developmental screenings, and adolescent wellness.',
    slotDurationMinutes: 30,
    workingHours: DEFAULT_WORKING_HOURS,
    leaveDays: [],
  },
  {
    id: 'doc_5',
    userId: 'usr_doc_5',
    name: 'Dr. Linda Gomez, MD',
    email: 'dr.gomez@healthmanager.clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&q=80&w=300',
    specialisation: 'Orthopedics',
    experienceYears: 13,
    consultationFee: 160,
    rating: 4.7,
    reviewCount: 88,
    roomNumber: 'Suite 112-C',
    bio: 'Orthopedic specialist in joint preservation, sports injuries, tendonitis, and non-surgical arthritis management.',
    slotDurationMinutes: 30,
    workingHours: DEFAULT_WORKING_HOURS,
    leaveDays: [],
  },
  {
    id: 'doc_6',
    userId: 'usr_doc_6',
    name: 'Dr. James Wilson, MD',
    email: 'dr.wilson@healthmanager.clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=300',
    specialisation: 'General Medicine',
    experienceYears: 8,
    consultationFee: 90,
    rating: 4.8,
    reviewCount: 142,
    roomNumber: 'Suite 101',
    bio: 'Primary care physician providing holistic family medicine, annual executive health checkups, and chronic condition oversight.',
    slotDurationMinutes: 20,
    workingHours: DEFAULT_WORKING_HOURS,
    leaveDays: [],
  },
];

export function getRelativeDateString(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
}

export const SEED_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt_001',
    doctorId: 'doc_1',
    patientId: 'usr_pat_1',
    doctorName: 'Dr. Sarah Smith, MD',
    doctorSpecialisation: 'Cardiology',
    patientName: 'Alex Johnson',
    patientEmail: 'alex.johnson@example.com',
    patientPhone: '+1 (555) 234-5678',
    appointmentDate: getRelativeDateString(0),
    startTime: '10:00',
    endTime: '10:30',
    status: 'CONFIRMED',
    consultationType: 'IN_PERSON',
    roomNumber: 'Suite 302-A',
    fee: 150,
    preVisitSummary: {
      urgencyLevel: 'Medium',
      chiefComplaint: 'Intermittent chest tightness and shortness of breath during brisk walking over the past 2 weeks.',
      suggestedQuestions: [
        'How frequently do the chest tightness episodes occur during physical exertion versus at rest?',
        'Are there accompanying symptoms like left arm numbness, dizziness, or sweating?',
        'Has there been any recent change in blood pressure or family history of coronary artery disease?',
      ],
      analyzedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
      symptomsRaw: 'Experiencing pressure-like chest tightness when climbing stairs or walking uphill for 2 weeks. Mild breathlessness, no radiating pain to jaw.',
      vitalSigns: {
        bloodPressure: '135/88 mmHg',
        heartRate: '78 bpm',
      },
    },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'apt_002',
    doctorId: 'doc_1',
    patientId: 'usr_pat_2',
    doctorName: 'Dr. Sarah Smith, MD',
    doctorSpecialisation: 'Cardiology',
    patientName: 'Emily Davis',
    patientEmail: 'emily.davis@example.com',
    patientPhone: '+1 (555) 345-6789',
    appointmentDate: getRelativeDateString(1),
    startTime: '11:00',
    endTime: '11:30',
    status: 'CONFIRMED',
    consultationType: 'IN_PERSON',
    roomNumber: 'Suite 302-A',
    fee: 150,
    preVisitSummary: {
      urgencyLevel: 'Low',
      chiefComplaint: 'Routine annual cardiovascular screening and cholesterol review.',
      suggestedQuestions: [
        'Have you noticed any fatigue or unusual heart fluttering in the past 6 months?',
        'What is your current dietary regimen and weekly aerobic exercise level?',
        'Do you have your most recent lipid profile lab reports from last year?',
      ],
      analyzedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
      symptomsRaw: 'No acute symptoms. Booking standard annual cardiology review. Slightly elevated total cholesterol reported 10 months ago.',
    },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'apt_003',
    doctorId: 'doc_2',
    patientId: 'usr_pat_1',
    doctorName: 'Dr. Marcus Vance, MD',
    doctorSpecialisation: 'Dermatology',
    patientName: 'Alex Johnson',
    patientEmail: 'alex.johnson@example.com',
    patientPhone: '+1 (555) 234-5678',
    appointmentDate: getRelativeDateString(-3),
    startTime: '14:00',
    endTime: '14:30',
    status: 'COMPLETED',
    consultationType: 'IN_PERSON',
    roomNumber: 'Suite 108',
    fee: 120,
    preVisitSummary: {
      urgencyLevel: 'Low',
      chiefComplaint: 'Red itchy circular patches on forearms and neck for 10 days.',
      suggestedQuestions: [
        'Did you come in contact with new detergents, cosmetics, or outdoor foliage?',
        'Is the itching worse at nighttime or after warm showers?',
        'Have over-the-counter moisturizers or hydrocortisone provided any relief?',
      ],
      analyzedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
      symptomsRaw: 'Itchy rash spreading across arms and neck since gardening last weekend.',
    },
    postVisitSummary: {
      clinicalDiagnosis: 'Subacute Allergic Contact Dermatitis with localized xerosis.',
      patientFriendlyExplanation: 'Your skin had an allergic reaction (contact dermatitis), likely triggered by exposure to outdoor plants or seasonal contact allergens. Your skin barrier is currently inflamed and dry.',
      medicationSchedule: [
        {
          id: 'med_001',
          medicineName: 'Mometasone Furoate 0.1% Cream',
          dosage: 'Thin layer apply',
          frequency: 'Once daily at night',
          durationDays: 7,
          instructions: 'Apply a very thin layer to affected red patches before bed. Do not apply on broken skin or near eyes.',
          scheduledTimes: ['09:00 PM'],
        },
        {
          id: 'med_002',
          medicineName: 'Cetirizine 10mg Tablets',
          dosage: '1 tablet',
          frequency: 'Once daily evening',
          durationDays: 5,
          instructions: 'Take with a glass of water after dinner to relieve itching.',
          scheduledTimes: ['08:00 PM'],
        },
      ],
      followUpSteps: [
        'Wash affected areas only with lukewarm water and fragrance-free soap.',
        'Apply gentle ceramide-based moisturizer liberally 3 times a day.',
        'Avoid scratching to prevent secondary bacterial infection.',
        'Book follow-up in 2 weeks if rash persists or worsens.',
      ],
      warningSigns: [
        'Spreading redness with warmth, pus discharge, or fever > 100.4°F.',
        'Swelling of the lips, eyes, or difficulty breathing (seek immediate emergency care).',
      ],
      nextVisitRecommendation: 'Follow up in 14 days if lesion margins remain erythematous.',
      generatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      doctorNotesRaw: 'Patient presents with erythematous maculopapular plaques on bilateral forearms. Dx: Contact Dermatitis. Rx: Mometasone 0.1% cream qhs x 7d, Cetirizine 10mg qd x 5d. Emollient barrier therapy advised. Re-eval in 2wks prn.',
    },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const SEED_MEDICATION_REMINDERS: MedicationReminder[] = [
  {
    id: 'rem_001',
    appointmentId: 'apt_003',
    patientId: 'usr_pat_1',
    patientName: 'Alex Johnson',
    patientEmail: 'alex.johnson@example.com',
    medicineName: 'Mometasone Furoate 0.1% Cream',
    dosage: 'Thin layer',
    scheduledTime: '09:00 PM',
    frequency: 'Once daily at night',
    startDate: getRelativeDateString(-3),
    endDate: getRelativeDateString(4),
    nextScheduledAt: `${getRelativeDateString(0)} 21:00`,
    status: 'ACTIVE',
  },
  {
    id: 'rem_002',
    appointmentId: 'apt_003',
    patientId: 'usr_pat_1',
    patientName: 'Alex Johnson',
    patientEmail: 'alex.johnson@example.com',
    medicineName: 'Cetirizine 10mg Tablets',
    dosage: '1 tablet',
    scheduledTime: '08:00 PM',
    frequency: 'Once daily evening',
    startDate: getRelativeDateString(-3),
    endDate: getRelativeDateString(2),
    nextScheduledAt: `${getRelativeDateString(0)} 20:00`,
    status: 'ACTIVE',
  },
];

export const SEED_NOTIFICATION_LOGS: NotificationLog[] = [
  {
    id: 'notif_001',
    recipientEmail: 'alex.johnson@example.com',
    recipientName: 'Alex Johnson',
    recipientRole: 'patient',
    type: 'BOOKING_CONFIRMATION',
    subject: 'Appointment Confirmed: Dr. Sarah Smith (Cardiology) on ' + getRelativeDateString(0),
    content: 'Dear Alex, your appointment with Dr. Sarah Smith is confirmed for today at 10:00 AM in Suite 302-A. Please arrive 10 minutes early.',
    status: 'SENT',
    retryCount: 0,
    sentAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'notif_002',
    recipientEmail: 'dr.smith@healthmanager.clinic',
    recipientName: 'Dr. Sarah Smith',
    recipientRole: 'doctor',
    type: 'BOOKING_CONFIRMATION',
    subject: 'New Patient Booking: Alex Johnson (Urgency: Medium)',
    content: 'Dr. Smith, Alex Johnson has booked a 30-min consultation for ' + getRelativeDateString(0) + ' at 10:00 AM. AI Pre-visit summary is available in your doctor portal.',
    status: 'SENT',
    retryCount: 0,
    sentAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'notif_003',
    recipientEmail: 'alex.johnson@example.com',
    recipientName: 'Alex Johnson',
    recipientRole: 'patient',
    type: 'MEDICATION_REMINDER',
    subject: 'Medication Reminder: Time for Cetirizine 10mg',
    content: 'Hi Alex, it is 08:00 PM. Please take 1 tablet of Cetirizine 10mg with water as prescribed by Dr. Marcus Vance.',
    status: 'SENT',
    retryCount: 0,
    sentAt: new Date(Date.now() - 86400000).toISOString(),
  },
];
